// ============================================================================
// VortekPreCoolingInject.inl
//
// Inline include — extracted from GCodeProcessor::run_post_process().
// Injects M104 lines generated by PreCoolingInjector at the matching line_id,
// and M73 E lines for remaining filament change counter.
//
// MUST be #include'd inside the main processing loop where
// precooling_iter, m_enable_pre_heating, line_id, export_line are in scope.
//
// BBL parity: BambuStudio GCodeProcessor.cpp (commit 3f2570c)
// ============================================================================

// H2C PreCooling + M73 E: inject lines from pre-scan phase
if (precooling_iter != precooling_inserted_lines.end()) {
    if (static_cast<int>(line_id) == precooling_iter->first) {
        for (auto& elem : precooling_iter->second) {
            const std::string& str = elem.first;
            const TimeProcessor::InsertLineType type = elem.second;
            switch (type) {
                case TimeProcessor::InsertLineType::PreCooling:
                case TimeProcessor::InsertLineType::PreHeating:
                    if (m_enable_pre_heating)
                        export_line.append_line(str);
                    break;
                case TimeProcessor::InsertLineType::FilamentChangePredict:
                    // M73 E — always inject for BBL printers
                    export_line.append_line(str);
                    break;
                default:
                    break;
            }
        }
        ++precooling_iter;
    }
}
